-- MySQL Script generated by MySQL Workbench
-- 12/13/16 09:16:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wakemeup
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wakemeup
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wakemeup` DEFAULT CHARACTER SET utf8 ;
USE `wakemeup` ;

-- -----------------------------------------------------
-- Table `wakemeup`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wakemeup`.`Users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `UserName` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(60) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `UserName_UNIQUE` (`UserName` ASC),
  INDEX `Email` (`Email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wakemeup`.`Settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wakemeup`.`Settings` (
  `idUser` INT NOT NULL,
  `CarSelected` TINYINT(1) NOT NULL,
  `BusSelected` TINYINT(1) NOT NULL,
  `BicycleSelected` TINYINT(1) NOT NULL,
  `PedSelected` TINYINT(1) NOT NULL,
  `Address` VARCHAR(45) NOT NULL,
  `PreparationTime` DOUBLE NOT NULL,
  `StudentId` INT NULL,
  `Weather` TINYINT(1) NULL,
  PRIMARY KEY (`idUser`),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `wakemeup`.`Users` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wakemeup`.`Subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wakemeup`.`Subjects` (
  `idSubject` INT NOT NULL,
  `SubjectName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idSubject`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wakemeup`.`Lecturer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wakemeup`.`Lecturer` (
  `idLecturer` INT NOT NULL,
  `LecturerName` VARCHAR(45) NULL,
  PRIMARY KEY (`idLecturer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wakemeup`.`Lectures`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wakemeup`.`Lectures` (
  `idLecture` INT NOT NULL,
  `idSubject` INT NOT NULL,
  `StartTime` TIME NOT NULL,
  `EndTime` TIME NOT NULL,
  `Day` INT NOT NULL,
  `Location` VARCHAR(45) NULL,
  `Practical` TINYINT(1) NOT NULL,
  `idLecturer` INT NOT NULL,
  PRIMARY KEY (`idLecture`),
  INDEX `Subject-Lecture_idx` (`idSubject` ASC),
  INDEX `Lecture-Lecturer_idx` (`idLecturer` ASC),
  CONSTRAINT `Subject-Lecture`
    FOREIGN KEY (`idSubject`)
    REFERENCES `wakemeup`.`Subjects` (`idSubject`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `Lecture-Lecturer`
    FOREIGN KEY (`idLecturer`)
    REFERENCES `wakemeup`.`Lecturer` (`idLecturer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wakemeup`.`TimeTable`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wakemeup`.`TimeTable` (
  `idUser` INT NOT NULL,
  `idLecture` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `TimeTable-Lecture_idx` (`idLecture` ASC),
  CONSTRAINT `UserTimeTable`
    FOREIGN KEY (`idUser`)
    REFERENCES `wakemeup`.`Users` (`idUser`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `TimeTable-Lecture`
    FOREIGN KEY (`idLecture`)
    REFERENCES `wakemeup`.`Lectures` (`idLecture`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wakemeup`.`verifyRegistration`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `wakemeup`.`verifyRegistration` (
  `Username` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NULL,
  `Password` VARCHAR(60) NULL,
  `Token` VARCHAR(96) NOT NULL,
  `TimeCreated` DATETIME NULL,
  `idUser` INT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
